### ISSUE TITLE
NodeSchool Wikimedia (Sep 21) #12

### ISSUE THREAD

**Issue by finnp** [nodeschool/berlin#20]
Hey everyone, 

there's another date we should keep in mind. It's http://wwwtf.berlin in September.

We should decide on a date for it and PR to: https://github.com/janl/wwwtf.berlin

Sign up: https://ti.to/nodeschool-berlin/12

#### TODOs
- [x] :calendar: Agree on a date 
- [x] :memo: Create ti.to page
- [x] :school: :bear: Post event on nodeschool.io  
- [x] :octocat: Inform on GiHub 
- [x] :monkey_face: :envelope: Inform about event through mail chimp
- [x] :bird: Tweet about the event
- [x] :house: Update homepage 
- [x] :alarm_clock: Send reminder to participants at the day of event 
- [x] :love_letter:  Write a follow up mail

Best,
Finn

**Comment by Realtin** [comment]
should we do this on a Monday as usually?
If yes, 21.September looks good.

**Comment by finnp** [comment]
I think, last time, we did it during JSConf.eu. Since most people involved with NodeSchool didn't have a ticket for this anyway. I would like to do at least this as close to the conferences as possible. There's no event on Wed, September 23rd yet.  So that would be an option. Otherwise Monday, 28th also seems like a good time.

So the options so far are:
- Mon, 21st September
- Wed, 23rd September
- Sat, 26th September (during CSSConf, whole day possible)
- Sun, 27th September (during JSConf.eu, whole day possible)
- Mon, 28th September

During wwwtf there will probably be a few more people around, so having a bigger venue like ZenMate or WikiMedia would be great I think.

**Comment by felixjung** [comment]
I'm on vacation on all these dates :cry:

**Comment by finnp** [comment]
I just contacted WikiMedia let's see if any of the dates work out for them.

**Comment by finnp** [comment]
Okay I just signed that we will use the room from 6pm to 9pm. \o/

**Comment by finnp** [comment]
Sponsoring
- Drinks and Location: 140 Euro
- Food: 110 Euro

**Comment by finnp** [comment]
Alright Asquera will pay drinks for tonight :)

**Comment by johannhof** [comment]
:+1:
