### ISSUE TITLE
Nodeschool #9 June Event

### ISSUE THREAD

**Issue by Realtin** [nodeschool/berlin#24]
### Date: Wednesday 17.06

RSVP at  https://ti.to/nodeschool-berlin/9

#### TODOs
- [x] :calendar: Agree on a date 
- [x] :memo: Create ti.to page
- [x] :school: :bear: Post event on nodeschool.io  
- [x] :octocat: Inform on GiHub 
- [x] :monkey_face: :envelope: Inform about event through mail chimp 
- [x] :house: Update homepage 
- [x] :alarm_clock: Send reminder to participants at the day of event

**Comment by finnp** [comment]
Thanks for creating this issue, love the emojis :cookie: 

At the last meetups, there have been rubymonstas who requested not to do it on Mondays. Maybe we we could find a Wednesday or Thursday instead. If there is no rug.b or berlin.js, thursday seems fine.

**Comment by finnp** [comment]
@stryju Maybe you can give feedback as well about what works for you.

**Comment by Realtin** [comment]
Ok I added Wednesdays and Thursdays to the list and alle the colliding events, that I know of.

**Comment by FerdousCodes** [comment]
I'm for 11.06 (Thursday) 😊

**Comment by stefania11** [comment]
I would be eternally grateful if we could do it any day before the 9th of June when I will be flying out to China :)

**Comment by hilja** [comment]
Loved Nodeschool last weekend, would like to participate again. Is it always at the same location?

**Comment by Realtin** [comment]
I left out the first week of June because I thought it might be too short notice, maybe not?

@hilja  Normaly we are at [Project A Ventures](https://www.google.com/maps/place/Julie-Wolfthorn-Stra%C3%9Fe+1,+10115+Berlin,+Germany/@52.532285,13.384316,16z/data=!4m2!3m1!1s0x47a851ed04b1eda9:0x74983279349a524a?hl=en-US)

**Comment by stryju** [comment]
hey there!

@chaeringer will take over for me from now on :-)

expect more infos soon

**Comment by chaeringer** [comment]
hello everybody!
the proposed Wednesdays would work for us and we would be happy to host it again at Project A Ventures.

**Comment by Realtin** [comment]
ok, would everyone be cool with **Wednesday 17.06**?

**Comment by marhigh** [comment]
That day works great for me :+1:

**Comment by finnp** [comment]
This works for me, too. Let's make if official?

@stefania11 and everyone else who might not be able to join: Maybe you could do some peer learning before the 9th of June, see #25

**Comment by FerdousCodes** [comment]
Works for me, too. 😄

**Comment by chaeringer** [comment]
:+1:  @finnp. Let's make if official.

**Comment by finnp** [comment]
Awesome.
![party](http://i.giphy.com/OSWRJKmwUEOD6.gif)

I created a sign up page for the event: https://ti.to/nodeschool-berlin/9
