### ISSUE TITLE
Nodeschool #10 (Whoop Whoop \o/) July Event

### ISSUE THREAD

**Issue by Realtin** [nodeschool/berlin#26]
Let's plan our next event!

#### TODOs
- [x] :calendar: Agree on a date 
- [x] :memo: Create ti.to page
- [x] :school: :bear: Post event on nodeschool.io  
- [x] :octocat: Inform on GiHub 
- [x] :monkey_face: :envelope: Inform about event through mail chimp
- [x] :bird: Tweet about the event
- [x] :house: Update homepage 
- [x] :alarm_clock: Send reminder to participants at the day of event 
- [ ] :calendar: Agree on a date for August

**Comment by Realtin** [comment]
**10th Nodeschool Berlin Event!**
![Whoop](http://media.giphy.com/media/zLoryjshXsQBa/giphy.gif)

**Comment by finnp** [comment]
So far all the dates work for me. If we do it at the 15th, it would be the same week as Berlin.js, which could be a date that we could use regularily. Would make this week a bit busy for javascripters, but I guess that's okay. 

@chaeringer @boennemann  How about you? Do these dates work for you?

**Comment by boennemann** [comment]
All dates work for me except for 29.07 :tada:

**Comment by chaeringer** [comment]
@finnp 15.07 works for me.

**Comment by boennemann** [comment]
There is now another (very interesting) event coming up on 15.7, so if it's still possible we might want to move to another date. http://lanyrd.com/2015/meetthetag/

**Comment by Realtin** [comment]
We need a new Date!!

**Comment by Realtin** [comment]
I propose: 
* Wed. 22.07
* Fri 24.07
* Wed 29.7

**Comment by finnp** [comment]
I only have time on the 29th.

**Comment by chaeringer** [comment]
Wed 29.7 works fine for me as well.

**Comment by finnp** [comment]
Okay great, so let's do this!

@boennemann I hope that works for you as well!

**Comment by Realtin** [comment]
great!

**Comment by chaeringer** [comment]
:+1:

**Comment by finnp** [comment]
@boennemann Ah I just saw the 29th doesn't work for you... So maybe in August then.

**Comment by felixjung** [comment]
@Realtin The only date that might work for me is the 29th. But I might to go on a business trip there.

**Comment by boennemann** [comment]
I'll be in Dublin on 29th, but I wish you all a good event. I'll join next time :)

**Comment by Realtin** [comment]
Tickets for the July Event are available! 
https://ti.to/nodeschool-berlin/10

I will write the Email this Weekend.

**Comment by finnp** [comment]
@Realtin Awesome :bee: Let me know if you need help with :email::monkey:

**Comment by finnp** [comment]
Thank you all for coming, sending the follow up mail now :love_letter: 

![](http://i.imgur.com/GSRdk.gif)
