### ISSUE TITLE
NodeSchool Event #11 in September

### ISSUE THREAD

**Issue by Realtin** [nodeschool/berlin#27]
There will be an Event for http://wwwtf.berlin at 21.09.15 (Mon)!
But we may want to have another one before that?

#### TODOs
- [x] :calendar: Agree on a date 
- [x] :memo: Create ti.to page
- [x] :school: :bear: Post event on nodeschool.io  
- [x] :octocat: Inform on GiHub 
- [x] :monkey_face: :envelope: Inform about event through mail chimp
- [x] :bird: Tweet about the event
- [x] :house: Update homepage 
- [x] :alarm_clock: Send reminder to participants at the day of event 
- [x] :love_letter:  Write a follow up mail

**Comment by Realtin** [comment]
I like the 07.09.

**Comment by finnp** [comment]
07.09. will not work for me. If there are enough mentors around that would be fine with me though.

How about doing it on a Wednesday like the last couple of times? 09.09. or 02.09. would be good fitting dates.

**Comment by finnp** [comment]
@boennemann @johannhof What dates work out best for you?

**Comment by boennemann** [comment]
2.9 busy moving into new apartment
6-10.9 nodeconf.eu

14.9 _could_ work

**Comment by Realtin** [comment]
I have my Clojure Project Group on Wednesdays. I *could* not go to one meeting but on the 9.9 is the Clojure Dojo where I want to go.

**Comment by Realtin** [comment]
02.09
pros: some RubyMonstas could join
cons: no Stephan; Julia misses her Clojure Projectgroup; maybe too short notice by now?

14.09
pros: maybe Stephan joins, it might be Berlin.js week, still time to organize stuff
cons: RubyMonstas are busy

so 02.09 vs 14.09  who will win?

**Comment by Realtin** [comment]
Ok so it's the 14.09!  is that cool with ProjectA ?
:)

**Comment by felixjung** [comment]
Awesome!

**Comment by chaeringer** [comment]
hello @Realtin, 
14.09 works for Project A Ventures. I will be at the smashing conf, but @PhilippWoe will take over for me.

**Comment by Realtin** [comment]
@chaeringer  @PhilippWoe ✨yay!

**Comment by PhilippWoe** [comment]
See you at the 14.09! Im looking forward :)

**Comment by Realtin** [comment]
should I add the event to the wwwtf also?

**Comment by Bolland** [comment]
Awesome will be there as well :)

**Comment by Realtin** [comment]
Ok here is the Event/Ticket Page: https://ti.to/nodeschool-berlin/11 
Finn sends out the Newsletter tomorrow \o/

**Comment by finnp** [comment]
Thanks everyone for coming! See you on monday at the [next event](https://ti.to/nodeschool-berlin/12)
