### ISSUE TITLE
NodeSchool #13 October @ Project A

### ISSUE THREAD

**Issue by finnp** [nodeschool/berlin#29]
Hey everyone :)

Let's start thinking about the next meetup. Any date suggestions?

October 22nd
https://ti.to/nodeschool-berlin/13

/cc @marhigh  @Realtin @boennemann

#### TODOs
- [x] :calendar: Agree on a date 22nd
- [x] :memo: Create ti.to page
- [x] :school: :bear: Post event on nodeschool.io  
- [x] :octocat: Inform on GiHub 
- [x] :monkey_face: :envelope: Inform about event through mail chimp
- [x] :bird: Tweet about the event
- [x] :house: Update homepage 
- [x] :alarm_clock: Send reminder to participants at the day of event 
- [x] :love_letter:  Write a follow up mail

**Comment by Realtin** [comment]
\o/  
I'll be at EuRuCo in Salzburg from 16th - 19th

**Comment by boennemann** [comment]
Only FullStack London upcoming 25-26th, otherwise I'm free :)

**Comment by Realtin** [comment]
How about Thursday the 22nd? it's one week after Berlinjs, we could make a short announcement there.

**Comment by marhigh** [comment]
That sounds good, I will ask to see if the lounge is available on Thursday the 22nd :)

**Comment by marhigh** [comment]
Thursday the 22nd is available at PAV, and booked! 
I would like to place some posters around the office so more people are aware of the event and perhaps want to join. Do you guys have any template or resources I could use?

**Comment by Realtin** [comment]
@marhigh  I could only find some images like the [nodeschool shoolbuilding](https://github.com/nodeschool/berlin/blob/gh-pages/schoollines_black.png) and the [Brandenburger Tor background from the website](https://github.com/nodeschool/berlin/blob/gh-pages/img/berlinbg.jpg)

**Comment by finnp** [comment]
Okay October 22nd sounds great.

@marhigh We don't have a general NodeSchool Berlin poster yet. @velchevski created a nice poster for the International Day event, there's a Sketch file online: https://github.com/nodeschool/berlin/blob/master/poster-international-day-2015.sketch. He also created this new logo which is pretty cool: https://d13yacurqjgara.cloudfront.net/users/48333/screenshots/2147503/nodeschool-berlin.png.

**Comment by Realtin** [comment]
@finnp oh I love the new logo!

**Comment by marhigh** [comment]
Thank you @Realtin and @finnp ! I will see what I can do with these and post here. 

Also, I contacted the catering company from the Reject JS health speaker and we will give it a try to have a healthier menu this time around. What they propose is the following:
Rice	paper spring rolls, Italian	antipasto skewers, Tortilla wedges	, Seasonal fruit salad skewers & Chocolate raspberry brownies.

Please let me know if you like the food this time around, if we get positive feedback I would like to continue with a healthier menu in the future. 

Have a nice weekend!

**Comment by finnp** [comment]
@marhigh That is a great idea!

Okay everybody: Here's a the sign up link for next Thursday: https://ti.to/nodeschool-berlin/13

**Comment by finnp** [comment]
Feedback link: http://goo.gl/forms/5juRp3ck0s

**Comment by finnp** [comment]
I've send an email where I also included a link to the new facebook group: https://www.facebook.com/groups/1512864689028358/.
