### ISSUE TITLE
NodeSchool #14 November @Project A

### ISSUE THREAD

**Issue by finnp** [nodeschool/berlin#32]
Hey everyone :)

Let's start thinking about the next meetup. Any date suggestions?

**26 November**

/cc @marhigh  @Realtin @boennemann @johannhof 

#### TODOs
- [x] :calendar: Agree on a date
- [x] :memo: Create ti.to page
- [x] :school: :bear: Post event on nodeschool.io  
- [x] :blue_book: Create facebook event
- [x] :octocat: Inform on GiHub 
- [x] :monkey_face: :envelope: Inform about event through mail chimp
- [ ] :bird: Tweet about the event
- [x] :house: Update homepage 
- [x] :alarm_clock: Send reminder to participants at the day of event 
- [x] :love_letter:  Write a follow up mail

**Comment by Realtin** [comment]
I really like Thursdays. **26.11** would be an option (it's the week *after* BerlinJS) or the **12.11** (the week *before* BerlinJS)

**Comment by boennemann** [comment]
26.11 would work for me, while 12.11 wouldn't.

**Comment by finnp** [comment]
I would prefer 26.11 as well.

**Comment by Realtin** [comment]
cool! so I guess 26.11 it is!

**Comment by marhigh** [comment]
Hi guys! Just checked with PAV and it's available, so 26.11 it is! 
@finnp

**Comment by tmundt** [comment]
This is great! When will we open the site to register/get tickets for the event?

**Comment by Realtin** [comment]
We usually do that ~1 week before the event ... It is just the sweetspot. Otherwise the 'no-show' rate is to high. 
This time we will also advertise via facebook and our new group.

**Comment by marhigh** [comment]
Hi y'all! I wrote this for the Facebook event. Its a little rough around the edges, but it's more or less the idea. Let me know what you think. I would like to get this up ASAP :) 

------------

Our monthly NodeSchool event is coming up! NodeSchool is a community-driven open source workshop for learning web software skills. 
Please read all of the information below and make sure to get a ticket if you want to attend :D

What you can expect: 
-> Self-guided exercises for every skill level
-> For absolute beginners: learn to use the terminal, git, and learn concepts that will allow you to understand the basics of Javascript and its many applications
-> For mid-level to advanced programmers: the sky is the limit! check out all the workshoppers available here: http://nodeschool.io/
-> Mentors available to answer your questions
-> Food and soft drinks sponsored by Project A

To register: 
-> Tickets are available 1 week before the event. The URL to get them will be posted here.
-> Please make sure you only get a ticket if you know you can come! Seats are limited and we want to make sure only those who can come take a spot.

Please note:  All our learning materials are self guided (you don't need to attend a workshop to do one) and most work offline.

Bring your laptop! And if you have any questions, feel free to message us. 

See you soon!

**Comment by marhigh** [comment]
FYI: New Facebook URL: https://www.facebook.com/groups/nodeschoolbln/

**Comment by Realtin** [comment]
@marhigh I like it! it covers all the important things.

**Comment by marhigh** [comment]
Ok guys, here is the event: https://www.facebook.com/events/917355215023468/?action_history=null
Let me know if there is anything else I can help out with between now and then :)

**Comment by Realtin** [comment]
Event is live on the Homepage
link to the tickets: https://ti.to/nodeschool-berlin/14

we should add the information to the facebook group right after we sent out the reminder emails

**Comment by marhigh** [comment]
Hello @Realtin & @finnp ! 
Could one of you please send me the estimated person count and the names of those confirmed so far? We usually need this for the office manager to register as part of the event. My email marimar.hollenbach@project-a.com. 
Thanks!

**Comment by finnp** [comment]
I just sent you the list :)
