### ISSUE TITLE
NodeSchool Event #15 in December

### ISSUE THREAD

**Issue by Realtin** [nodeschool/berlin#33]
**December 8th**

![Finn & Jake](https://media.giphy.com/media/vyi7qpUrCTHr2/giphy.gif)

**TODOs**

- [x] :calendar: Agree on a date
- [x] :memo: Create ti.to page
- [x] :school: :bear: Post event on nodeschool.io
- [x] :blue_book: Create facebook event
- [x] :octocat: Inform on GiHub
- [x] :monkey_face: :envelope: Inform about event through mail chimp
- [x] :bird: Tweet about the event
- [x] :house: Update homepage
- [ ] :email: send attendee list to mar
- [ ] :alarm_clock: Send reminder to participants at the day of event
- [ ] :love_letter: Write a follow up mail

**Comment by marhigh** [comment]
Hi guys! I am unfortunately not available on the 10th. Would the 8th or 9th work for you? I'll also have to check if the lounge is available.

**Comment by finnp** [comment]
8th and 9th works for me.

**Comment by Realtin** [comment]
I would favour the 8th over the 9th.

**Comment by marhigh** [comment]
Ok, the 8th it is! I just booked the lounge.

**Comment by Realtin** [comment]
\o/

**Comment by finnp** [comment]
Kewl! I am going to bring some cookies :cookie: :cookie:

**Comment by Realtin** [comment]
[Rainbow Heart Cookies?](http://www.instructions.tips/how-to-make-rainbow-heart-cookies/) :rainbow:

**Comment by Realtin** [comment]
signups are ready: https://ti.to/nodeschool-berlin/15

**Comment by Realtin** [comment]
send the wrong link in the mail /o\

**Comment by finnp** [comment]
We are not fully booked yet, I tweeted to link so maybe this will help.
