### ISSUE TITLE
NodeSchool #16 in January

### ISSUE THREAD

**Issue by finnp** [nodeschool/berlin#34]
Hey everyone! 

I hope you all had a great christmas. Let's think about when to do the NodeSchool in January. Last year we thought about doing it in the end of January, but we @diasdavid is going to be in Berlin in the first two weeks of January. So maybe we could do it a bit earlier? Let me know what works for you!

*26th January*

/cc @marhigh  @Realtin @boennemann @johannhof  @lislis

**TODOs**

- [x] :calendar: Agree on a date
- [x] :memo: Create ti.to page
- [x] :school: :bear: Post event on nodeschool.io
- [x] :blue_book: Create facebook event
- [x] :octocat: Inform on GiHub
- [x] :cool:  add event to the Hoodie Events Calender
- [x] :monkey_face: :envelope: Inform about event through mail chimp
- [x] :bird: Tweet about the event
- [x] :house: Update homepage
- [x] :email: send attendee list to mar
- [x] :alarm_clock: Send reminder to participants at the day of event
- [x] :love_letter: Write a follow up mail

**Comment by johannhof** [comment]
:tada:

I can probably make it in January, blocked date for me is only Wednesday Jan 13 (Rust Hack and Learn)

**Comment by boennemann** [comment]
I'm back in Berlin by January 17th, so I'm out for this one.
Have fun :)

**Comment by Realtin** [comment]
Jan 14 will probably be the Coaches Meeting for ClojureBridge but otherwise I'm available!

**Comment by diasdavid** [comment]
This sounds awesome! Adding @whyrusleeping to the thread as he will be travelling with me. 1st week (till the 7~8th of January) will be the best dates for us :)

**Comment by diasdavid** [comment]
Update: We will be on our way to Copenhagen on the 6th, we can do some Nodeschool or Node Meetup for some hacking and catching up on the 5th, how does that sound? :)

**Comment by marhigh** [comment]
Hi guys! I'm not in the office until the 5th, making it not the best date, also considering I need a bit of time to reserve the lounge and plan food once I'm back at work. I am a big fan of planning it later in the month when the holiday craze has settled and people have returned from holidays.

**Comment by finnp** [comment]
Yeah let's do the next NodeSchool at the end of January as we originally planned then.

@diasdavid I started 2016 off by being sick :/ So we'll probably not have a chance to meet up. I hope you are having a great time in Berlin!

**Comment by diasdavid** [comment]
@finnp hope you are feeling better. We will be later today at c-base doing IPFS sprint discussions, you are welcome to join us if you have the chance :)

**Comment by marhigh** [comment]
How about Thursday the 21st or 28th? (pending on availability of the lounge)

**Comment by Realtin** [comment]
21st is Berlin.js
28th is ["The Strange Group"](http://www.meetup.com/de-DE/Strange-Group-Berlin/events/227361679/) I have never been there but it sounds pretty cool.  
What dou you all think about **Tue 26th**?

**Comment by marhigh** [comment]
That would work for me. How about for everyone else? I will check if the lounge is also available.

**Comment by finnp** [comment]
26th works for me.

**Comment by johannhof** [comment]
:+1:

**Comment by marhigh** [comment]
Wonderful. The lounge is now booked for Tuesday, the 26th at 7 p.m.
This time around we'll have pizza again, to have warm food in this cold weather. See you then!

**Comment by Realtin** [comment]
💻🍕💻🍕💻🍕💻🍕💻🍕💻🍕💻🍕💻🍕💻🍕💻🍕💻🍕💻🍕💻🍕💻🍕💻🍕💻🍕💻🍕💻🍕💻🍕💻🍕💻🍕💻🍕💻🍕💻🍕💻🍕💻🍕💻🍕💻🍕💻🍕💻🍕💻🍕💻🍕💻🍕💻🍕

**Comment by marhigh** [comment]
Just created the FB event: https://www.facebook.com/events/1539758513001164/

About "Send reminder to participants at the day of event" -> what do you guys think about switching this to 2 days before? I worry that a reminder the day of the event might be too late.

**Comment by finnp** [comment]
@marhigh Yeah I could do that. Generally I feel like the day of the event is the best one (assuming you don't want to send multiple emails) because the people who need this kind of reminders are usually the ones that will also not remember it if it's happening the day after tomorrow. Also most people get push notifications for their emails, so they get a reminder directly to their phone.

**Comment by boennemann** [comment]
26th :white_check_mark:

**Comment by Realtin** [comment]
https://ti.to/nodeschool-berlin/16

**Comment by Realtin** [comment]
I'll add NodeSchool from now on to the http://hood.ie/events/ !

**Comment by finnp** [comment]
Thanks everyone for coming :heart:
