### ISSUE TITLE
NodeSchool #17 in February

### ISSUE THREAD

**Issue by finnp** [nodeschool/berlin#37]
Hey everyone! 

**23rd February**

/cc @marhigh  @Realtin @boennemann @johannhof

**TODOs**

- [x] :calendar: Agree on a date
- [x] :memo: Create ti.to page
- [x] :school: :bear: Post event on nodeschool.io
- [x] :blue_book: Create facebook event
- [x] :speech_balloon:  Post to slack channel 
- [x] :octocat: Inform on GiHub
- [x] :cool:  add event to the Hoodie Events Calender
- [ ] :monkey_face: :envelope: Inform about event through mail chimp
- [ ] :bird: Tweet about the event
- [x] :house: Update homepage
- [x] :email: send attendee list to mar
- [ ] :alarm_clock: Send reminder to participants at the day of event
- [ ] :love_letter: Write a follow up mail

**Comment by marhigh** [comment]
i'm available both days.

**Comment by Realtin** [comment]
the 23rd is also Node.js Meetup (I don't know anyone that likes this meetup so... it might not really be competing with us)
Otherwise I think I'll be available on both days.

**Comment by supernoir** [comment]
Feb 23rd should work (conflicting with two other meetups/groups tho), thus Feb 25th would be better.

**Comment by johannhof** [comment]
I can't make it on the 25th, but if that date fits better then don't mind me :sweat_smile:

**Comment by finnp** [comment]
Let's go for *23rd of February*!

**Comment by johannhof** [comment]
:exclamation:

**Comment by felixjung** [comment]
Looks like a good day to me :+1:

**Comment by marhigh** [comment]
Okay guys the PAV lounge is booked, and I will create the FB event & the event on OTS' meetup page at some point today.

**Comment by marhigh** [comment]
FB event: https://www.facebook.com/events/1701941396749113/

**Comment by Realtin** [comment]
https://ti.to/nodeschool-berlin/17
