### ISSUE TITLE
NodeSchool #18 in March

### ISSUE THREAD

**Issue by finnp** [nodeschool/berlin#40]
Hey everyone! 

How about March 22nd for the next meetup?

/cc @marhigh  @Realtin @boennemann @johannhof

**TODOs**

- [x] :calendar: Agree on a date
- [x] :memo: Create ti.to page
- [x] :school: :bear: Post event on nodeschool.io
- [x] :blue_book: Create facebook event
- [x] :speech_balloon:  Post to slack channel 
- [x] :octocat: Inform on GiHub
- [x] :cool:  add event to the Hoodie Events Calender
- [x] :monkey_face: :envelope: Inform about event through mail chimp
- [x] :bird: Tweet about the event
- [x] :house: Update homepage
- [x] :email: send attendee list to mar
- [x] :alarm_clock: Send reminder to participants at the day of event
- [x] :love_letter: Write a follow up mail

**Comment by marhigh** [comment]
:+1:

**Comment by Realtin** [comment]
sounds good!

**Comment by finnp** [comment]
cool

**Comment by felixjung** [comment]
:+1:

**Comment by finnp** [comment]
SIgn up is open https://ti.to/nodeschool-berlin/18 :tada:

**Comment by marhigh** [comment]
FB event: https://www.facebook.com/events/568946746603796/

**Comment by marhigh** [comment]
Meetup event: http://www.meetup.com/opentechschool-berlin/events/229661023/

**Comment by finnp** [comment]
:love_letter:
